version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/nginx-no-ssl/conf.d:/etc/nginx/conf.d
      - ./data/certbot/www:/var/lib/letsencrypt
