version: '3.8'

services:
  nginx_ssl:
    image: nginx:latest
    container_name: nginx_ssl
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../certifications/live:/etc/letsencrypt/live:ro
      - ../certifications/archive:/etc/letsencrypt/archive:ro

